<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Created By Descending</name>
   <tag></tag>
   <elementGuidId>79a41efb-bd8d-4592-b3ea-06cdb1c743cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-21']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-21 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6267e67a-9e77-4d76-a08a-033659eef850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>0468ba28-7a31-409b-8114-bfa9c3115853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Created By : Descending </value>
      <webElementGuid>576e96e0-d5a8-4d08-9ff9-b8ba1cd1e6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-21&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>cb0702c3-4d55-450b-abe1-733d7d5f2931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-21']/span</value>
      <webElementGuid>d246dda7-8baa-47cb-b725-9866327edb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By : Ascending'])[1]/following::span[1]</value>
      <webElementGuid>fb2e0734-3eaa-4770-bbac-317ac254cdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposed Loan Amount : High to Low'])[1]/following::span[2]</value>
      <webElementGuid>00e628bb-3076-4bde-992f-fe51111ee976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Name : Ascending'])[1]/preceding::span[1]</value>
      <webElementGuid>18d3e3cc-0c3b-43cf-a275-3dff5724923f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Name : Descending'])[1]/preceding::span[2]</value>
      <webElementGuid>1ff75c5b-2cd9-498a-b52f-0c3b3e2f684b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Created By : Descending']/parent::*</value>
      <webElementGuid>30bec98b-35e1-42b4-92bd-be4f78af2007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/mat-option[2]/span</value>
      <webElementGuid>2ead13c1-0c62-40fe-8b57-c983a545fb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Created By : Descending ' or . = ' Created By : Descending ')]</value>
      <webElementGuid>32454cdb-b70e-4a2e-b300-638453795938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
