<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Created By Ascending</name>
   <tag></tag>
   <elementGuidId>3e533c70-5712-4531-ba4a-6d89a9fb3a5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mat-option-20&quot;]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-20 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>916faf7e-7b9c-4624-9523-cc2e57bb4aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>445a769d-8ebe-431b-82ae-d69257efc180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Created By : Ascending </value>
      <webElementGuid>8f0f995a-8131-43d1-b059-e07850374070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-20&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>185292a7-d537-494f-8e53-58f71a1996af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-20']/span</value>
      <webElementGuid>c7def09a-5ac5-48af-95e2-108383ec4579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposed Loan Amount : High to Low'])[1]/following::span[1]</value>
      <webElementGuid>d5ee4878-bf06-41d3-838b-b16ad24421b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposed Loan Amount : Low to High'])[1]/following::span[2]</value>
      <webElementGuid>99e7574c-6d3a-4f65-8f02-e1ea45bc3610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By : Descending'])[1]/preceding::span[1]</value>
      <webElementGuid>1e0b3619-9ea5-484f-ba1b-8629b9d1c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Name : Ascending'])[1]/preceding::span[2]</value>
      <webElementGuid>16952281-8461-496f-9f81-596664256ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Created By : Ascending']/parent::*</value>
      <webElementGuid>d080b990-cc5a-4bb2-8c75-3cfb2b3b0a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/mat-option/span</value>
      <webElementGuid>d258acd0-ffaf-4740-9558-3d19e522bd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Created By : Ascending ' or . = ' Created By : Ascending ')]</value>
      <webElementGuid>31e58e49-ce7b-47fc-9ccc-43d9a6d62fad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
