<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Entity Name Ascending</name>
   <tag></tag>
   <elementGuidId>9448534c-4b19-4f9d-9033-ec224692f34e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-22']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-22 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05591821-798c-42f7-a9a0-76400f339536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>17c840be-9ef7-4abd-9770-43953cbbf440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Entity Name : Ascending </value>
      <webElementGuid>1e06862e-4596-4ece-94da-4949996e48e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-22&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>772f73d0-9db3-44e3-9000-2b8400806991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-22']/span</value>
      <webElementGuid>f118f4ad-323a-44be-a766-e0adbd83ebac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By : Descending'])[1]/following::span[1]</value>
      <webElementGuid>ab7b7d16-c43a-4089-8867-8758d650851d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By : Ascending'])[1]/following::span[2]</value>
      <webElementGuid>808bd4e5-b77a-456a-af89-057698343e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Name : Descending'])[1]/preceding::span[1]</value>
      <webElementGuid>57de6848-6090-48d0-a7ba-cc047cded1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entity Name : Ascending']/parent::*</value>
      <webElementGuid>59959e41-6292-4c84-878e-b28f678d4124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/mat-option/span</value>
      <webElementGuid>127875ee-d7ef-4c2c-b8cc-0dc5f692904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Entity Name : Ascending ' or . = ' Entity Name : Ascending ')]</value>
      <webElementGuid>52b0202e-74fc-4d1e-b6f2-02a2cb5a56b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
