<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Entity Name Descending</name>
   <tag></tag>
   <elementGuidId>e4f7a006-1c8b-4957-a315-db75cdbc6885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-23']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-23 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab2571a4-7c65-41fb-ab5e-8aabeb1a56b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>72663737-0164-4233-b437-61f85eacb5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Entity Name : Descending </value>
      <webElementGuid>c9a742c5-98bd-4a21-bd9c-6b5fd416c177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-23&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>120a4fa7-1ca2-44c6-a411-ab45b7083d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-23']/span</value>
      <webElementGuid>ddc138d5-b167-40ac-8591-07c1d395a768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Name : Ascending'])[1]/following::span[1]</value>
      <webElementGuid>c0b67a9d-5bcb-4f96-82b9-5edd9c877d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By : Descending'])[1]/following::span[2]</value>
      <webElementGuid>17882ea7-1663-4beb-8416-61bc814be633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entity Name : Descending']/parent::*</value>
      <webElementGuid>1c90823e-3809-42ea-92db-1989240a34e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/mat-option[2]/span</value>
      <webElementGuid>d65548c7-9872-4c43-b04f-acbe3c6627cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Entity Name : Descending ' or . = ' Entity Name : Descending ')]</value>
      <webElementGuid>d5b702b4-232e-4f23-b069-cdc916ef4cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
