<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proposals</name>
   <tag></tag>
   <elementGuidId>ff0458aa-ec3f-480a-86df-411ba5ed7016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Proposals')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.links</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca2c4f89-c2c2-4942-8e44-9419ec9e14d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0cea23bc-575a-4357-9f11-38b2c34ad1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>links</value>
      <webElementGuid>37872a5e-9ac6-453c-bef6-2971db94ead5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entities</value>
      <webElementGuid>d901576b-4d10-4b19-b260-321eb86f23a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-app-background&quot;]/anchors-root[1]/anchors-anchors-container[@class=&quot;ng-star-inserted&quot;]/anchors-applications[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;application-container&quot;]/anchors-side-nav[1]/section[@class=&quot;navigation&quot;]/nav[@class=&quot;side-nav-container&quot;]/ul[1]/li[3]/div[@class=&quot;entity_hover&quot;]/div[@class=&quot;rowAlign&quot;]/div[@class=&quot;col-md-6 menubarcol&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-content&quot;]/a[@class=&quot;links&quot;]</value>
      <webElementGuid>58977b13-dd32-4aee-aa9c-46b3ef18b2db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entities')]</value>
      <webElementGuid>de24aa23-3cfe-43b7-be1a-e326293aecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity'])[1]/following::a[1]</value>
      <webElementGuid>0b88fa92-2db9-4c14-b36b-d89c64e47a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[1]/following::a[1]</value>
      <webElementGuid>6c25b4a6-3d3c-4219-b48c-9088591a46ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposals'])[1]/preceding::a[1]</value>
      <webElementGuid>c4ecad11-5b1c-40ef-b322-05682f999986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bharmagowda B S'])[1]/preceding::a[2]</value>
      <webElementGuid>755d0bb4-056c-4faf-afbc-c3ce1ac8bed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entities']/parent::*</value>
      <webElementGuid>be6c2771-4010-4657-8047-8c4adc667d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>a061d766-2e01-48ba-82e6-998cd0d4264b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>5ec283a2-4f59-4f93-b552-04d420bbf56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Entities' or . = 'Entities')]</value>
      <webElementGuid>4320b41d-ad6c-4135-a61f-55eb134668c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
