<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//span[normalize-space()='Partnership']</description>
   <name>FirmType_Partnership</name>
   <tag></tag>
   <elementGuidId>cc895376-0fa0-41e4-8f9a-d45141d76e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Partnership']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
