<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit(invoice)</name>
   <tag></tag>
   <elementGuidId>dba6e0c4-0f60-4695-8601-c019891b343a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//anchors-member-section[10]//anchors-forms[1]//anchors-form-builder[1]//div[1]//div[1]//button[1]//span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
