<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Current Years In Current Address</name>
   <tag></tag>
   <elementGuidId>5bd7a380-1cd7-441b-800d-670f3f068a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-current-address-yearsInCurrentAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-current-address-yearsInCurrentAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b8597c5-ad82-4f1c-b3bc-5d21faa982b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8706f798-35f3-4a8e-ab1e-1bab7acad600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-36 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>86d2646d-6285-4623-a721-6dd679141d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-current-address-yearsInCurrentAddress</value>
      <webElementGuid>4f0404c6-159a-405f-9449-1cc69eedc55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: 2/3/4</value>
      <webElementGuid>b12fff44-83f9-4556-a563-78abf7aa9558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed25354f-c2f5-4bce-9f5c-929a1946c5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a300c38e-3c17-4329-8581-5338013b1c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 2/3/4</value>
      <webElementGuid>28da8703-7030-4777-b090-27c6b1d6854d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-current-address-yearsInCurrentAddress&quot;)</value>
      <webElementGuid>4d1d7929-42ad-4c38-83e3-d62a52d56e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-current-address-yearsInCurrentAddress']</value>
      <webElementGuid>0e111f09-adee-4342-962e-826cd3bf97ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[5]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div[2]/form/jkf-element-builder[10]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>d60d64d2-f4cb-4f69-9e98-9e1987a45d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>dd52fcab-4448-40d1-bac3-cd7000343e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'en-sec-client-current-address-yearsInCurrentAddress' and @placeholder = 'Ex: 2/3/4']</value>
      <webElementGuid>cec1e88b-b179-417b-a546-bda43e8867cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
