<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Current Longitude</name>
   <tag></tag>
   <elementGuidId>08293e8f-ae8e-41b4-99ce-586d685305dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-current-address-longitude']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-current-address-longitude</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6a5dcb9-e021-464e-9348-766d7c234796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7710d419-6db4-4de2-83e6-784ce124e67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-38 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>70f5845f-02bf-4c1a-92d0-50d27ad52694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-current-address-longitude</value>
      <webElementGuid>1dccbf1d-56c3-4568-b76b-1d8a0854e85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: 0.02452</value>
      <webElementGuid>b7b47788-ac48-4abb-9c45-150d70fb56bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d304857-b43b-4368-b333-62a06a369459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7b821f4-4b72-420c-a144-37454515d0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 0.02452</value>
      <webElementGuid>bb894f8b-b17d-4fe2-8984-fbd8af160d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-current-address-longitude&quot;)</value>
      <webElementGuid>084ba640-a857-4ab4-8a5e-cf9da4ed7d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-current-address-longitude']</value>
      <webElementGuid>070bbbf4-4081-4f4d-95da-e49677dba11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[5]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div[2]/form/jkf-element-builder[12]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>ec41f7f4-211d-42b3-ba1b-8e5160fe0931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[12]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>6e3aaaa4-e76f-446c-aca4-0d7f466ad967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'en-sec-client-current-address-longitude' and @placeholder = 'Ex: 0.02452']</value>
      <webElementGuid>6785182f-0a02-4861-8cec-c8212f8165b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
