<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Street Address2</name>
   <tag></tag>
   <elementGuidId>03969f62-abf3-4159-a51e-78a5ed0462fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-permanent-address-streetAddress2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-permanent-address-streetAddress2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>540dcd8b-547e-44f3-8623-1669abd81089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9f0701a-bdfe-464c-9136-42f5d96ea5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-33 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>e0955614-1705-4f9f-b52f-40ffd9a17556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-permanent-address-streetAddress2</value>
      <webElementGuid>c1299a8b-a763-463e-8a72-f13eea291b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: D-block, Vikaspuri</value>
      <webElementGuid>93a7e540-f875-4f3e-8597-c13386614953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f0f8c12-bd4f-4b74-af21-7973043e50de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>670cb81c-0e48-49b2-8dcf-6cad24bbf992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: D-block, Vikaspuri</value>
      <webElementGuid>d0ae9d67-79be-4caf-9d12-cc6fab7e3a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-permanent-address-streetAddress2&quot;)</value>
      <webElementGuid>899dada0-cd17-4b25-8a7a-18392b5745e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-permanent-address-streetAddress2']</value>
      <webElementGuid>fda48187-e8cd-410d-b5cb-ad1637375c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[4]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder[8]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>561ff4fa-b3d9-407c-8aaa-1a3175cd734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[8]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>f5e633cd-3767-4a77-be05-d73fa14960a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'en-sec-client-permanent-address-streetAddress2' and @placeholder = 'Ex: D-block, Vikaspuri']</value>
      <webElementGuid>77c44102-4b1a-4c3d-a869-3f8c5fe7f641</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
