<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Longitude</name>
   <tag></tag>
   <elementGuidId>70b7b96d-8097-4e15-b481-a4860dee922c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-permanent-address-longitude']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-permanent-address-longitude</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96a2afba-0eaa-4e61-af80-0dc7dad4ee79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fecf6362-1ac1-419e-a26f-f10643dc6f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-38 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>f6a4751e-ca35-40d3-9ea6-d2cb03802773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-permanent-address-longitude</value>
      <webElementGuid>042d9476-cdda-4cef-b805-5a2408a5406c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: 0.02452</value>
      <webElementGuid>fa7e0cd0-af90-43f4-bdb1-0550e56035aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b969179-bb73-4554-adf5-95ae2c16ddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c543b7b7-b45c-438a-86b2-aa1548739129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 0.02452</value>
      <webElementGuid>34287ad2-8e83-48c6-b5a1-8e6d53a1bf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-permanent-address-longitude&quot;)</value>
      <webElementGuid>5ff13ba5-5679-44d0-a98c-987c4a31dc9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-permanent-address-longitude']</value>
      <webElementGuid>270b1a11-763c-4a5c-9f72-703ffa693182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[4]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder[12]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>7697f46d-c611-446e-8409-2ba1fe4f9a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[12]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>24da0048-79e1-4787-a3f7-15b38d200738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'en-sec-client-permanent-address-longitude' and @placeholder = 'Ex: 0.02452']</value>
      <webElementGuid>b4638ac8-f370-44ba-912d-8ee9875e3df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
