<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Village</name>
   <tag></tag>
   <elementGuidId>10abdc00-33cf-4688-8f26-4b278537a6b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-permanent-address-village']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-permanent-address-village</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c48e5b8-a2d2-4dbb-ab55-c4e409e90a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed46aa3c-070f-418e-b958-0cfae001bed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-30 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>69d91284-fab6-4265-b219-8ee6d48a63c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-permanent-address-village</value>
      <webElementGuid>3c87cdc1-7c1b-4503-9fd1-00dac8d8b2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex Haryana</value>
      <webElementGuid>5a1f5fcb-a59f-4fc2-b21e-bf4ee2b68557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1eec660c-636d-479b-9930-c998d93da3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d8909f7-2681-4469-831c-00773813a182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex Haryana</value>
      <webElementGuid>3ad09b5f-04b1-458a-95fc-4cd30f9a6954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-permanent-address-village&quot;)</value>
      <webElementGuid>42c07d07-864d-4937-bbbe-cc4caeab6bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-permanent-address-village']</value>
      <webElementGuid>eb0c8555-e292-4f1a-a4d0-b4f7ce95657b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[4]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder[5]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>349eb058-e9ce-4521-a936-b840247bc528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[5]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>1aacd3b9-28cc-4a46-ab0e-63971512f1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'en-sec-client-permanent-address-village' and @placeholder = 'Ex Haryana']</value>
      <webElementGuid>ff2ccfa2-7de2-415e-8f28-53fc6a5d24cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
