<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Pincode</name>
   <tag></tag>
   <elementGuidId>048f0a0b-1a81-42f7-a6db-c2375a50f778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-permanent-address-pincode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-permanent-address-pincode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdb71bbb-742f-4093-8b11-401a59c94d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>708331ce-957c-422f-82d7-d5486ca0fc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-26 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>234d9166-0bac-4833-aae5-6bec44842e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-permanent-address-pincode</value>
      <webElementGuid>19f1d7ce-aae6-45c8-bbc5-985b642f2e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Enter Pincode</value>
      <webElementGuid>5db6629d-a12a-4057-b350-a34263c96271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1ff81a5-f06d-442f-af3d-dcdcbf0855c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25710780-7fe2-4a00-8be8-71dd61916ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Pincode</value>
      <webElementGuid>e3d66487-0cc4-4897-b66b-86c76b6f8cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-permanent-address-pincode&quot;)</value>
      <webElementGuid>3e0cf597-b723-45f4-adcf-a490d0bd5dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-permanent-address-pincode']</value>
      <webElementGuid>17282399-9ec5-47b1-bc3a-c7d331312b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[4]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>da0c985d-ed4a-4612-ad57-71096ccc429d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2441f6de-2ce5-403c-b785-9c61f1e93049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'en-sec-client-permanent-address-pincode' and @placeholder = 'Enter Pincode']</value>
      <webElementGuid>b90e1f2d-be00-488f-b8ac-5f9decb21a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
