<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Years In Current Address</name>
   <tag></tag>
   <elementGuidId>c9a94628-b190-410f-9ce4-31138cfcc65c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-permanent-address-yearsInCurrentAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-permanent-address-yearsInCurrentAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c7b656b-8bad-427e-baba-9e3cd3d9adbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d12904b6-1f92-4208-84a8-39b3032d66a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-36 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>f580ebdf-2166-40b4-9b3c-9b0c3029db09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-permanent-address-yearsInCurrentAddress</value>
      <webElementGuid>7aad842a-25a8-4557-8d8d-8da1617c8c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: 2/3/4</value>
      <webElementGuid>603231af-f08e-4317-9d0b-ca70239e7ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0bc84f1-8436-44a1-887c-b57b9d38cef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>094ea285-58e8-4484-a8f3-b8f149e6d234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 2/3/4</value>
      <webElementGuid>6465e60b-3c4c-4955-a9a4-85be696730c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-permanent-address-yearsInCurrentAddress&quot;)</value>
      <webElementGuid>33568645-eda8-4f98-a300-609b01022697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-permanent-address-yearsInCurrentAddress']</value>
      <webElementGuid>73888baa-29ab-4f8f-97cd-65529c123fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[4]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder[10]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>3838daf9-7e6a-4ea2-9e5c-a3b830ae0919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>3efb90b4-0705-454d-a1bb-c814e869e94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'en-sec-client-permanent-address-yearsInCurrentAddress' and @placeholder = 'Ex: 2/3/4']</value>
      <webElementGuid>62855513-db9c-4d8f-a89b-559689e004a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
