<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Primary Contact</name>
   <tag></tag>
   <elementGuidId>db2307ff-73e3-420d-957b-9e2f38d9ecb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-icon-button.mat-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.mat-tooltip-trigger.iconAlign.material-icons.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='newPrimaryContact']/button/span/mat-icon)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>ac95a39d-c07b-4b41-a974-9e623f685e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7affa0b5-7ee9-4cfd-a2e1-c65c7a18c142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mat-tooltip-trigger iconAlign material-icons mat-icon-no-color</value>
      <webElementGuid>a63c1bfe-1367-4751-8037-9514b83b3b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8178a0b4-c1bc-4e4d-b030-9d48f9d7eaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>436866b4-c150-4781-a622-382bb45a8b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-8</value>
      <webElementGuid>d14a71c9-7f07-4ef8-9ee4-27cca2063781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>star</value>
      <webElementGuid>1f8f2d24-3c67-44b4-a833-122d27347066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-5&quot;)/anchors-member[@class=&quot;ng-star-inserted&quot;]/section[1]/anchors-member-section[@class=&quot;ng-star-inserted&quot;]/anchors-forms[@class=&quot;ng-star-inserted&quot;]/anchors-form-builder[1]/div[@class=&quot;jkf-container ng-star-inserted&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/jkf-element-builder[@class=&quot;ng-star-inserted&quot;]/anchors-wrapper-element[@class=&quot;ng-star-inserted&quot;]/jkf-toggle-input[@class=&quot;ng-star-inserted&quot;]/div[@id=&quot;newPrimaryContact&quot;]/button[@class=&quot;mat-focus-indicator mat-icon-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate mat-tooltip-trigger iconAlign material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>11cabc03-617f-431c-990a-8c0ddf013dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='newPrimaryContact']/button/span/mat-icon)[2]</value>
      <webElementGuid>cfa58949-af2b-4c50-b653-d7a3d0624bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[5]/anchors-wrapper-element/jkf-toggle-input/div/button/span/mat-icon</value>
      <webElementGuid>b1ecfca2-120c-4fd1-ac94-d5c61d5e70d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'star' or . = 'star')]</value>
      <webElementGuid>6bef8fe1-bb29-4c2e-9333-8dbd11d7bb1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
