<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>59e23f28-d2e8-4341-bca5-1d609631b7f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/anchors-root[1]/anchors-anchors-container[1]/anchors-application-details[1]/div[1]/div[3]/div[1]/mat-tab-group[1]/div[1]/mat-tab-body[5]/div[1]/div[1]/anchors-section-renderer[1]/div[1]/anchors-content-decider[1]/anchors-member-details[1]/div[1]/anchors-table[1]/div[1]/div[2]/div[1]/anchors-table-search[1]/section[1]/form[1]/mat-form-field[1]/div[1]/div[1]/div[2]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
