<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Email</name>
   <tag></tag>
   <elementGuidId>828c71de-cb69-45a8-a0c0-852ab28b6480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-onboarding-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-onboarding-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53710b2a-1dc4-4995-b2a7-9e19de590dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96523f60-c9e7-4444-8900-736c7b607db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-7 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-invalid</value>
      <webElementGuid>4d4e7980-c645-4103-beba-caa1b669c926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-onboarding-email</value>
      <webElementGuid>c0360f52-2b9a-4760-b6c4-ba64d18e2fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: abc@gmail.com</value>
      <webElementGuid>4d19aabe-e498-4975-9210-5ee234029ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52245063-8bc4-4ace-b657-533c1c968999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1b61a86-e775-4ad1-8005-f75af154d4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: abc@gmail.com</value>
      <webElementGuid>967919db-806a-4f4d-9008-ddbcf7159431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-onboarding-email&quot;)</value>
      <webElementGuid>219a5ede-5408-4e89-8ce2-b00656ad07a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-onboarding-email']</value>
      <webElementGuid>56c92db8-45b6-4798-b6ef-165dd6655a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alignClientsField']/form/jkf-element-builder[3]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>6faa7d08-baf8-4cae-95d7-dfb4aaf4dc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[3]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>68987530-3af7-4c7a-8d3e-bf81fa429ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'en-sec-client-onboarding-email' and @placeholder = 'Ex: abc@gmail.com']</value>
      <webElementGuid>bd2670a3-554c-4838-b92c-99632a0a30d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
