<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Aadhar Number</name>
   <tag></tag>
   <elementGuidId>fddb3fb1-25cc-4fbd-9c59-8e2f97d7b3d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-additional-details-uidNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-additional-details-uidNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc6d0e97-44a4-4bc4-beb2-aa541c7cb728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcdbd7a3-d57b-49a9-a69d-8a6197607f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-20 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>31ab7c1e-367e-4f36-9273-b55eb97ebfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-additional-details-uidNo</value>
      <webElementGuid>996f8c24-ab1f-4cf3-bcd6-5524e97cbe61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Ex: 8171 7599 5946</value>
      <webElementGuid>f8f0c8dd-22df-40cc-9923-e9875befa499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69d1e373-801c-4817-a983-312db79b3eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d422f14b-51ec-4d61-8fd1-c09e0d4ebfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 8171 7599 5946</value>
      <webElementGuid>6950d8bb-5a45-4da5-a1ec-7e9de224fb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-additional-details-uidNo&quot;)</value>
      <webElementGuid>43cd15f7-d43e-4d0e-8210-abbb65c23ce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-additional-details-uidNo']</value>
      <webElementGuid>bc85ffbb-a287-49d1-a3cc-faadd2bbd7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[3]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder[4]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>3833ec45-5edd-4806-9fcb-257f53abc1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[4]/anchors-wrapper-element/anchors-text-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>51e34e40-c4b0-4be4-8294-ef4effd19f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'en-sec-client-additional-details-uidNo' and @placeholder = 'Ex: 8171 7599 5946']</value>
      <webElementGuid>9c7b9514-5ed5-49a2-bd22-1d7db77e6300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
