<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Annual Income</name>
   <tag></tag>
   <elementGuidId>3833c95e-fe7a-48db-a24c-41d79d9b6bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='en-sec-client-additional-details-annualIncome']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en-sec-client-additional-details-annualIncome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69cf0842-2397-48c2-9619-1775d1a1df11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e2341468-58b2-4eba-b048-1f7abe5fdca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c134-26 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>3d7a64e7-09a8-4ed8-82ec-46088c5e3b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en-sec-client-additional-details-annualIncome</value>
      <webElementGuid>79a8dae4-c2c5-44f7-ae40-5cc5f463b625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>250000</value>
      <webElementGuid>894456f0-2c70-4900-9954-6c1f6819b2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0bca812-9ee7-4a8f-a405-aa7be3a017b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60fadc12-e968-48e8-848b-ae5fdcc36c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>250000</value>
      <webElementGuid>a41ab3db-2e0d-4e7b-8bf1-5a0ff92690d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-client-additional-details-annualIncome&quot;)</value>
      <webElementGuid>af89a028-0d42-4e31-b92a-b3d796cbb2db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='en-sec-client-additional-details-annualIncome']</value>
      <webElementGuid>320ed4f2-0611-4858-9588-dae401aa30a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/anchors-section-renderer/div/div/div[3]/div/div/anchors-content-decider/anchors-forms/anchors-form-builder/div/form/jkf-element-builder[9]/anchors-wrapper-element/anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>68474353-378f-4c5a-af99-2b4141faf2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//anchors-number-input/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>06310fde-9934-41fc-b1e4-3ceff2ed47cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'en-sec-client-additional-details-annualIncome' and @placeholder = '250000']</value>
      <webElementGuid>d9748680-bc7c-4a09-8495-bbed4a18b1e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
