<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//span[contains(text(),'Female')]</description>
   <name>dropdown_gender</name>
   <tag></tag>
   <elementGuidId>7f7a0038-ad3f-41d8-ba61-17d8faae2d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Female')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
