<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_datepickerArrow</name>
   <tag></tag>
   <elementGuidId>d73cd5e1-86ff-4360-bc64-d02bb670b468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c121-34</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='en-sec-guarantor-info-gender']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c121-34</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en-sec-guarantor-info-gender&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c121-34&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c121-34&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c121-34&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='en-sec-guarantor-info-gender']/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//jkf-element-builder[7]/anchors-wrapper-element/anchors-select-input/div/mat-form-field/div/div/div[3]/mat-select/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
