<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Username or email</name>
   <tag></tag>
   <elementGuidId>2f8ce1ea-3060-45eb-9699-9a06e8d98b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.control-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kc-form-login']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>de3a684a-5d26-4ba0-a689-547e5e06614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>582c15ad-d8c8-4b52-baa0-0ae4c0fa8834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>5ba73d7c-4b73-488f-9288-4c3f58ba56b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username or email</value>
      <webElementGuid>1283e664-64eb-40c9-90ba-69617725517b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-form-login&quot;)/div[@class=&quot;form-group&quot;]/label[@class=&quot;control-label&quot;]</value>
      <webElementGuid>0ea20925-0eae-41b2-ab37-e281a813517e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div/label</value>
      <webElementGuid>13796e9d-6978-46f1-a5fd-552ec9a0f451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In with Jai Kisan Credentials provided'])[1]/following::label[1]</value>
      <webElementGuid>965fe12f-f123-4796-b83a-83590da75734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jai-Kisan.in Users'])[1]/following::label[1]</value>
      <webElementGuid>7d1ac05b-eec8-4bcb-9d4c-961e23dcc749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::label[1]</value>
      <webElementGuid>5d6800fb-46c4-4e15-bf88-39e55d06b013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::label[2]</value>
      <webElementGuid>fe37f439-cc06-4d26-baab-e5d744fefc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username or email']/parent::*</value>
      <webElementGuid>487e6452-a35e-49fb-8db1-c08a15988478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>a35f8d37-2758-49e0-8479-cd9fb4c7927c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Username or email' or . = 'Username or email')]</value>
      <webElementGuid>04d88d13-3ea1-4e17-9ff7-7c1d6b2e6414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
