<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Activation_StageMapping_Edit</name>
   <tag></tag>
   <elementGuidId>7a272226-0c64-4a6d-b467-9f89858e7acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mat-dialog-12&quot;]/anchors-member/section/anchors-member-section[6]/anchors-forms/anchors-form-builder/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
