<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_StageMapping_Edit</name>
   <tag></tag>
   <elementGuidId>e8d31fe8-0f54-4a47-8841-05133528b0d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mat-dialog-1&quot;]/anchors-member/section/anchors-member-section[6]/anchors-forms/anchors-form-builder/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
