<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Channel Legal Name Ascending</name>
   <tag></tag>
   <elementGuidId>d2f6c1fc-441d-4818-985a-be481c196e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-6']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-6 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64f4eea8-4c30-4bca-8f33-d515c4782897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>39142158-9a39-4b3e-a294-141151c60d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Channel Legal Name : Ascending </value>
      <webElementGuid>388312da-76a4-4a75-aec7-96d50e1697d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-6&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>583bca93-9715-4ae7-a7c9-6d4026432dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-6']/span</value>
      <webElementGuid>74b59516-d687-422f-855b-e01322b3cd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated : Latest'])[1]/following::span[1]</value>
      <webElementGuid>25b0293e-6b5f-4d73-b68c-d69907f5a815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated : Oldest'])[1]/following::span[2]</value>
      <webElementGuid>22c475f9-ff1b-4da7-8340-d89095b552b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Legal Name : Descending'])[1]/preceding::span[1]</value>
      <webElementGuid>d73e0116-d7c3-4986-b9bd-01aa3314b11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Channel Legal Name : Ascending']/parent::*</value>
      <webElementGuid>41e3cf40-9a6f-44c3-a682-e496150ca269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/mat-option/span</value>
      <webElementGuid>387fa554-ff59-45f8-9efe-5bd79418811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Channel Legal Name : Ascending ' or . = ' Channel Legal Name : Ascending ')]</value>
      <webElementGuid>a75dbce9-0f30-402a-bbcd-b465d6e60258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
