<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proposals - Sort By</name>
   <tag></tag>
   <elementGuidId>aea1f36e-0de8-41d0-abb3-bd34ff8cb527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-7']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-select-placeholder.ng-tns-c136-29.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95d8d433-f140-4b95-9cfc-60d2bdf58612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-placeholder ng-tns-c136-29 ng-star-inserted</value>
      <webElementGuid>07605333-7510-480f-9b61-f3fc63f2a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>869e0fd5-8e67-441b-9d38-0c8a93a7609a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-7&quot;)/span[@class=&quot;mat-select-placeholder ng-tns-c136-29 ng-star-inserted&quot;]</value>
      <webElementGuid>bd6e055a-0fd3-4c8c-b158-951302640c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-7']/span</value>
      <webElementGuid>12b29072-b94a-4a28-908c-961e581d1e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Proposal by Product ID, Proposal Name, Loan Product, Entity Name, Lender'])[1]/following::span[2]</value>
      <webElementGuid>a05dc9e0-a730-4ef1-bd50-af154fef4d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associated Clients'])[1]/following::span[3]</value>
      <webElementGuid>5a32c548-772c-4f48-84cd-d433b2c5acdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::span[1]</value>
      <webElementGuid>e76b3a51-0ad0-4cdc-94b3-a392ab412602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div/span</value>
      <webElementGuid>bb16b97c-0063-4862-9bf5-5e26f79eaf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>a01bc576-30a8-48cf-a6a8-88cfa2ea360a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
