<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proposal - Exposure Limit High to Low (1)</name>
   <tag></tag>
   <elementGuidId>cb39ec5f-da3b-4fff-85d5-2740ba702c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-21']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-21 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfdd5bc0-19f9-4ebb-9cd9-b10416405f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>f3c8c934-2fd5-4197-bffe-c234dd3ed73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Exposure Limit : High to Low </value>
      <webElementGuid>54c2c58f-8a5f-413e-bdb6-b00d16768487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-21&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>eb7e392e-f9e5-4923-a330-0d71077d5aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-21']/span</value>
      <webElementGuid>c571e7c3-1a0d-4aaf-8da7-ce42c05ab8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exposure Limit : Low to High'])[1]/following::span[1]</value>
      <webElementGuid>9575b4ef-7df6-48b6-9065-e3ccf8051bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remaining Credit Limit : High to Low'])[1]/following::span[2]</value>
      <webElementGuid>57c46e73-4dac-45a7-8e9a-dd6cb81f903c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposal Name : Ascending'])[1]/preceding::span[1]</value>
      <webElementGuid>47a6479a-3f59-4383-b672-09cc0ae170a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposal Name : Descending'])[1]/preceding::span[2]</value>
      <webElementGuid>094763a7-997e-4b14-a331-43804241f94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exposure Limit : High to Low']/parent::*</value>
      <webElementGuid>f3d6e11d-cc91-41f6-9dd6-cf23f6f31e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/mat-option[2]/span</value>
      <webElementGuid>b47bded4-aadf-49bc-88e3-a1042c893958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Exposure Limit : High to Low ' or . = ' Exposure Limit : High to Low ')]</value>
      <webElementGuid>45298972-2700-4c84-bb91-616f14e4f1ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
