<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Store - Sort By</name>
   <tag></tag>
   <elementGuidId>0ea947aa-8f0d-43d5-a426-5cdd5aa2a3d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mat-select-value-7&quot;]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-select-placeholder.ng-tns-c136-29.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d788d23-5239-4305-9e42-849b5abfc9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-placeholder ng-tns-c136-29 ng-star-inserted</value>
      <webElementGuid>dd91dc13-6273-49ed-b346-adaaf8f867f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>14def576-84b8-4b8d-885a-f01e607ab9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-7&quot;)/span[@class=&quot;mat-select-placeholder ng-tns-c136-29 ng-star-inserted&quot;]</value>
      <webElementGuid>48c39a31-b397-47ec-b168-0bbe266fedc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-7']/span</value>
      <webElementGuid>72942f95-bf67-474e-80a7-863cac15835f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Store'])[1]/following::span[2]</value>
      <webElementGuid>88d812ac-1bd4-4089-af28-449bd822fd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store Details List'])[1]/following::span[3]</value>
      <webElementGuid>9e6a7235-78d5-4a4a-a59a-878806eb7822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[2]/preceding::span[1]</value>
      <webElementGuid>c00faf02-f449-443a-833f-8acbe9f30501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/mat-form-field/div/div/div/mat-select/div/div/span</value>
      <webElementGuid>8b1d9353-8895-4004-bee0-0775c3943afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>59546dc1-aab5-4155-9cb8-5d889067841d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
